wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714069957.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.13
      5: 0.16.6
      6: 4.39.2
      8:
      - 1
      - 5
      13: linux-x86_64
