wandb_version: 1

architecture:
  desc: null
  value: bert
context:
  desc: null
  value: concatenated
input shape:
  desc: null
  value: flattened
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 1.0e-05
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713809971.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.6
      6: 4.39.2
      8:
      - 1
      - 5
      13: linux-x86_64
